package com.muchlis.inventaris.utils

//const val INTERNET_SERVER = "http://10.4.2.21:5001"
const val INTERNET_SERVER = "https://risa.muchlis.dev" //222.124.218.221

const val ERR_JSON_PARSING = "Parsing JSON Response gagal"
const val ERR_CONN = "Gagal terhubung ke server"
const val ERR_DROPDOWN_NOT_LOAD = "Dropdown status tidak berhasil di load"
const val ERR_FORM_NOT_VALID = "Harap lengkapi formulir"

const val CATEGORY_PC = "PC"
const val CATEGORY_CCTV = "CCTV"
const val CATEGORY_STOCK = "STOCK"
const val CATEGORY_DAILY = "DAILY"
const val CATEGORY_APPLICATION = "APPLICATION"
const val CATEGORY_TABLET = "HANDHELD"

const val SEMUA = "---"
const val YA = "YA"
const val TIDAK = "TIDAK"
const val AKTIF = "AKTIF"
const val NONAKTIF = "NONAKTIF"
const val YES = "yes"
const val NO = "no"
const val LAINNYA = "LAINNYA"
const val UP = "UP"
const val DOWN = "DOWN"


const val INTENT_TO_HISTORY_CREATE_ID = "INTENT_TO_HISTORY_CREATE_ID"
const val INTENT_TO_HISTORY_CREATE_CATEGORY = "INTENT_TO_HISTORY_CREATE_CATEGORY"
const val INTENT_TO_HISTORY_CREATE_NAME = "INTENT_TO_HISTORY_CREATE_NAME"

const val INTENT_PC_TO_DETAIL = "INTENT_PC_TO_DETAIL"
const val INTENT_TO_EDIT_COMPUTER = "INTENT_TO_EDIT_COMPUTER"

const val INTENT_STOCK_TO_DETAIL = "INTENT_STOCK_TO_DETAIL"
const val INTENT_RESULT_STOCK = "INTENT_RESULT_STOCK"
const val INTENT_TO_STOCK_USE_CREATE_ID = "INTENT_TO_STOCK_USE_CREATE_ID"
const val INTENT_TO_STOCK_USE_MODE = "INTENT_TO_STOCK_USE_MODE"
const val INTENT_TO_STOCK_USE_NAME = "INTENT_TO_STOCK_USE_NAME"
const val INCREMENT_MODE = "INCREMENT"
const val DECREMENT_MODE = "DECREMENT"
const val INTENT_TO_EDIT_STOCK = "INTENT_TO_EDIT_STOCK"

const val INTENT_CCTV_TO_DETAIL = "INTENT_CCTV_TO_DETAIL"
const val INTENT_TO_EDIT_CCTV = "INTENT_TO_EDIT_CCTV"

const val INTENT_PELINDO_HISTORY_TO_EDIT = "INTENT_PELINDO_HISTORY_TO_EDIT"


const val INTENT_HH_TO_DETAIL = "INTENT_HH_TO_DETAIL"
const val INTENT_TO_EDIT_HH = "INTENT_TO_EDIT_HANDHELD"

